node_name 'docker_node'
checksum_path '/etc/chef/checksums'
file_cache_path '/etc/chef/cache'
file_backup_path '/etc/chef/backup'
cookbook_path '/etc/chef/cookbooks'
data_bag_path '/etc/chef/data_bags'
environment_path '/etc/chef/environments'
role_path '/etc/chef/roles'
chef_server_url 'http://127.0.0.1:8889'
encrypted_data_bag_secret '/etc/chef/data_bags/encrypted_data_bag_secret'
log_level :info
log_location '/var/log/chef-client.log'
verify_api_cert false
