checksum_path '/etc/chef/checksums'
#chef_server_url 'http://127.0.0.1:8889'
chef_zero.enabled true
cookbook_path '/etc/chef/cookbooks'
data_bag_path '/etc/chef/data_bags'
encrypted_data_bag_secret '/etc/chef/data_bags/encrypted_data_bag_secret'
environment_path '/etc/chef/environments'
file_backup_path '/etc/chef/backup'
file_cache_path '/etc/chef/cache'
local_mode true
log_level :info
log_location '/var/log/chef-client.log'
node_name 'docker_node'
role_path '/etc/chef/roles'
verify_api_cert false
