---

driver:
  name: vagrant
  customize:
    memory: 512
    cpus: 1
  driver_config:
    ssl_verify_mode: ":verify_none"

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.18.31
  client_rb:
    ssl_verify_mode: ":verify_none"
  data_bags_path: "test/data_bags"
  encrypted_data_bag_secret_key_path: "test/data_bags/encrypted_data_bag_secret"
  roles_path: "test/roles"
  environments_path: "test/environments"

platforms:
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: base
    run_list:
      - role[base]
    verifier:
      inspec_tests:
        - name: bootstrap
          git: https://github.com/bonusbits/inspec_bootstrap.git
#        - name: bonusbits_base
#          git: https://github.com/bonusbits/inspec_bonusbits_base.git
        - path: /Users/levon/Development/github/bonusbits/inspec_bonusbits_base
      attributes:
        chef_version: 12.18.31
    includes: ["centos-6.8", "centos-7.2", "ubuntu-14.04", "ubuntu-16.04"]
    provisioner:
      client_rb:
        environment: "bonusbits_base"
  - name: base_epel_repo
    run_list:
      - role[base]
    includes: ["centos-6.8", "centos-7.2"]
    provisioner:
      client_rb:
        environment: "bonusbits_base_epel_repo"
  - name: base_firewall
    run_list:
      - role[base]
    includes: ["centos-6.8", "centos-7.2"]
    provisioner:
      client_rb:
        environment: "bonusbits_base_firewall"
  - name: base_no_software
    run_list:
      - role[base]
    includes: ["centos-6.8", "centos-7.2", "ubuntu-14.04", "ubuntu-16.04"]
    provisioner:
      client_rb:
        environment: "bonusbits_base_no_software"
  - name: base_proxy
    run_list:
      - role[base]
    includes: ["centos-6.8", "centos-7.2", "ubuntu-14.04", "ubuntu-16.04"]
    provisioner:
      client_rb:
        environment: "bonusbits_base_proxy"
