---

# YAML Anchors - Shared Values
anchors:
  # AWS Account
  aws_tag_owner: &aws_tag_owner <%= ENV.fetch('USER', 'bonusbits') %>

platforms:
  # AWS AMI/EC2 Platforms
  - name: amazon-linux1-ami
    driver:
      associate_public_ip: <%= ENV.fetch('AWS_PUBLIC_IP', 'false') %>
      aws_ssh_key_id: <%= ENV.fetch('AWS_SSH_KEY_ID', 'bonusbits_dev_key') %>
      iam_profile_name: <%= ENV.fetch('AWS_IAM_INSTANCE_PROFILE_LNX', 'Linux-Instance_Role') %>
      image_search:
        owner-id: 137112412989
        name: amzn-ami-hvm-2018.03.0.20190826-x86_64-gp2
      instance_initiated_shutdown_behavior: terminate
      instance_type: t3.micro
      name: ec2
      region: <%= ENV.fetch('AWS_REGION', 'us-west-2') %>
      security_group_ids:
        - <%= ENV.fetch('AWS_SECURITY_GROUP_lnx_1', 'sg-00000000') %>
        - <%= ENV.fetch('AWS_SECURITY_GROUP_lnx_2', 'sg-00000000') %>
      subnet_id: <%= ENV.fetch('AWS_SUBNET_ID', 'subnet-00000000') %>
      tags:
        Created-By: Test Kitchen
        OS: Amazon v1
        Owner: *aws_tag_owner
      # user_data: *bootstrap_lnx
      vpc_id: <%= ENV.fetch('AWS_VPC_ID', 'vpc-00000000') %>
    transport:
      username: ec2-user
      ssh_key: <%= ENV.fetch('AWS_SSH_KEY_PATH', ENV['HOME'] + "/.ssh/bonusbits_dev_key.pem") %>
  - name: amazon-linux2-ami
    driver:
      associate_public_ip: <%= ENV.fetch('AWS_PUBLIC_IP', 'false') %>
      aws_ssh_key_id: <%= ENV.fetch('AWS_SSH_KEY_ID', 'bonusbits_dev_key') %>
      iam_profile_name: <%= ENV.fetch('AWS_IAM_INSTANCE_PROFILE_LNX', 'Linux-Instance_Role') %>
      image_search:
        owner-id: 137112412989
        name: amzn2-ami-hvm-2.0.20190823.1-x86_64-gp2
      instance_initiated_shutdown_behavior: terminate
      instance_type: t3.micro
      name: ec2
      region: <%= ENV.fetch('AWS_REGION', 'us-west-2') %>
      security_group_ids:
        - <%= ENV.fetch('AWS_SECURITY_GROUP_lnx_1', 'sg-00000000') %>
        - <%= ENV.fetch('AWS_SECURITY_GROUP_lnx_2', 'sg-00000000') %>
      subnet_id: <%= ENV.fetch('AWS_SUBNET_ID', 'subnet-00000000') %>
      tags:
        Created-By: Test Kitchen
        OS: Amazon v2
        Owner: *aws_tag_owner
      # user_data: *bootstrap_lnx
      vpc_id: <%= ENV.fetch('AWS_VPC_ID', 'vpc-00000000') %>
    transport:
      username: ec2-user
      ssh_key: <%= ENV.fetch('AWS_SSH_KEY_PATH', ENV['HOME'] + "/.ssh/bonusbits_dev_key.pem") %>
  - name: ubuntu-1604-ami
    driver:
      associate_public_ip: <%= ENV.fetch('AWS_PUBLIC_IP', 'false') %>
      aws_ssh_key_id: <%= ENV.fetch('AWS_SSH_KEY_ID', 'bonusbits_dev_key') %>
      iam_profile_name: <%= ENV.fetch('AWS_IAM_INSTANCE_PROFILE_LNX', 'Linux-Instance_Role') %>
      image_search:
        owner-id: 099720109477
        name: ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20190913
      instance_initiated_shutdown_behavior: terminate
      instance_type: t3.micro
      name: ec2
      region: <%= ENV.fetch('AWS_REGION', 'us-west-2') %>
      security_group_ids:
        - <%= ENV.fetch('AWS_SECURITY_GROUP_lnx_1', 'sg-00000000') %>
        - <%= ENV.fetch('AWS_SECURITY_GROUP_lnx_2', 'sg-00000000') %>
      subnet_id: <%= ENV.fetch('AWS_SUBNET_ID', 'subnet-00000000') %>
      tags:
        Created-By: Test Kitchen
        OS: Ubuntu 16.04 LTS
        Owner: *aws_tag_owner
      # user_data: *bootstrap_lnx
      vpc_id: <%= ENV.fetch('AWS_VPC_ID', 'vpc-00000000') %>
    transport:
      username: ubuntu
      ssh_key: <%= ENV.fetch('AWS_SSH_KEY_PATH', ENV['HOME'] + "/.ssh/bonusbits_dev_key.pem") %>
  - name: ubuntu-1804-ami
    driver:
      associate_public_ip: <%= ENV.fetch('AWS_PUBLIC_IP', 'false') %>
      aws_ssh_key_id: <%= ENV.fetch('AWS_SSH_KEY_ID', 'bonusbits_dev_key') %>
      iam_profile_name: <%= ENV.fetch('AWS_IAM_INSTANCE_PROFILE_LNX', 'Linux-Instance_Role') %>
      image_search:
        owner-id: 099720109477
        name: ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-20191002
      instance_initiated_shutdown_behavior: terminate
      instance_type: t3.micro
      name: ec2
      region: <%= ENV.fetch('AWS_REGION', 'us-west-2') %>
      security_group_ids:
        - <%= ENV.fetch('AWS_SECURITY_GROUP_lnx_1', 'sg-00000000') %>
        - <%= ENV.fetch('AWS_SECURITY_GROUP_lnx_2', 'sg-00000000') %>
      subnet_id: <%= ENV.fetch('AWS_SUBNET_ID', 'subnet-00000000') %>
      tags:
        Created-By: Test Kitchen
        OS: Ubuntu 18.04 LTS
        Owner: *aws_tag_owner
      # user_data: *bootstrap_lnx
      vpc_id: <%= ENV.fetch('AWS_VPC_ID', 'vpc-00000000') %>
    transport:
      username: ubuntu
      ssh_key: <%= ENV.fetch('AWS_SSH_KEY_PATH', ENV['HOME'] + "/.ssh/bonusbits_dev_key.pem") %>

  # Docker Platforms
  - name: amazon-linux1-docker
    driver:
      name: docker
      use_sudo: false
      # Amazon Linux AMI 2018.03 (v1 - el6)
      # https://hub.docker.com/_/amazonlinux
      # image: amazonlinux:1-with-sources
      image: amazonlinux:2018.03.0.20190826-with-sources
      platform: rhel
      provision_command:
        # - echo "export http_proxy=<%= ENV['http_proxy']%>" > /etc/profile.d/proxy.sh
        # - echo "export https_proxy=<%= ENV['https_proxy']%>" >> /etc/profile.d/proxy.sh
        # - echo "export no_proxy=<%= ENV['no_proxy']%>" >> /etc/profile.d/proxy.sh
        # - export http_proxy="<%= ENV['http_proxy']%>"
        # - export https_proxy="<%= ENV['https_proxy']%>"
        # - export no_proxy="<%= ENV['no_proxy']%>"
        - yum -y install upstart procps util-linux
      ssl_verify_mode: ":verify_none"
      # http_proxy: <%= ENV['http_proxy']%>
      # https_proxy: <%= ENV['https_proxy']%>
      # no_proxy: <%= ENV['no_proxy']%>
  - name: amazon-linux2-docker
    driver:
      name: docker
      use_sudo: false
      # SystemD Privilege workaround
      privileged: true
      run_command: /usr/sbin/init
      # Amazon Linux AMI 2018.03 (v2 - el7 - systemd)
      # https://hub.docker.com/_/amazonlinux
      image: amazonlinux:2.0.20190823.1-with-sources
      platform: rhel # Still needed Test Kitchen v2.3.3 for Amazon Linux
      provision_command:
        - yum -y install procps util-linux
      ssl_verify_mode: ":verify_none"
  - name: ubuntu-1604-docker
    driver:
      name: docker
      use_sudo: false
      # Ubuntu 16.04 LTS Xenial
      # https://hub.docker.com/_/ubuntu
      image: ubuntu:16.04
      ssl_verify_mode: ":verify_none"
  - name: ubuntu-1804-docker
    driver:
      name: docker
      use_sudo: false
      # Ubuntu 18.04 LTS Bionic
      # https://hub.docker.com/_/ubuntu
      image: ubuntu:18.04
      ssl_verify_mode: ":verify_none"
  - name: ubuntu-2004-docker
    driver:
      name: docker
      use_sudo: false
      # Ubuntu 20.04 LTS Focal
      # https://hub.docker.com/_/ubuntu
      image: ubuntu:20.04
      ssl_verify_mode: ":verify_none"

provisioner:
  data_bags_path: "test/data_bags"
  # download_url: https://packages.chef.io/files/current/chefdk/4.5.0/el/7/chefdk-4.5.0-1.el7.x86_64.rpm
  encrypted_data_bag_secret_key_path: "test/data_bags/encrypted_data_bag_secret"
  environments_path: "test/environments"
  name: chef_zero
  product_name: chefdk
  product_version: 4.5.0
  roles_path: "test/roles"

suites:
  - name: docker_base
    attributes:
      <% if ENV['CIRCLECI'] %>
      bonusbits_base:
        deployment_location: 'circleci'
      <% end %>
    includes: ["amazon-linux1-docker", "amazon-linux2-docker"]
    provisioner:
      client_rb:
        environment: bonusbits_base
    run_list:
      - role[base]

  - name: docker_base_java
    attributes:
      <% if ENV['CIRCLECI'] %>
      bonusbits_base:
        deployment_location: 'circleci'
      <% end %>
    includes: ["amazon-linux1-docker", "amazon-linux2-docker"]
    provisioner:
      client_rb:
        environment: bonusbits_base_java
    run_list:
      - role[base]

  - name: docker_base_no_software
    attributes:
      <% if ENV['CIRCLECI'] %>
      bonusbits_base:
        deployment_location: 'circleci'
      <% end %>
    includes: ["amazon-linux1-docker", "amazon-linux2-docker"]
    provisioner:
      client_rb:
        environment: bonusbits_base_no_software
    run_list:
      - role[base]

  - name: ec2_base
    provisioner:
      client_rb:
        environment: bonusbits_base
    driver:
      tags:
        Name: kitchen-bonusbits-base-<%= ENV['USER'] %>
    run_list:
      - role[base]
    includes: ["amazon-linux1-ami", "amazon-linux2-ami"]

  - name: ec2_base_java
    provisioner:
      client_rb:
        environment: bonusbits_base_java
    driver:
      tags:
        Name: kitchen-bonusbits-base-<%= ENV['USER'] %>
    run_list:
      - role[base]
    includes: ["amazon-linux1-ami", "amazon-linux2-ami"]

  - name: ec2_base_no_software
    provisioner:
      client_rb:
        environment: bonusbits_base_no_software
    driver:
      tags:
        Name: kitchen-bonusbits-base-no-software<%= ENV['USER'] %>
        Created-By: Test Kitchen
        Owner: *aws_tag_owner
    run_list:
      - role[base]
    includes: ["amazon-linux1-ami", "amazon-linux2-ami"]

verifier:
  inputs:
    debug: true
    test_chef: true
    chef_client_version: '15.4.45'
    chef_dk_version: '4.5.0'
  inspec_tests:
    - name: bonusbits_base
      git: https://github.com/bonusbits/inspec_bonusbits_base.git
      release: 2.1.0
    #- path: ../inspec_bonusbits_base
  name: inspec
  reporter:
    - cli
  <% if ENV['CI'] %>
    - junit:reports/integration/%{platform}_%{suite}_inspec.xml
  <% end %>
