AlignParameters:
  Enabled: false

AllCops:
  # Version on /opt/chefdk/embedded/bin/ruby --version
  TargetRubyVersion: 2.6.5
  Exclude:
    - 'berks-cookbooks/**/*'
    - '.idea/**/*'
    - '.git/**/*'
    - '.kitchen/**/*'
    - '*.lock'
    - 'vendor/**/*'
    - 'tmp/**/*'

CaseIndentation:
  IndentOneStep: false

CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 28

Metrics/LineLength:
  Max: 256

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 128
  CountComments: false

Metrics/PerceivedComplexity:
  Max: 10

Style/Encoding:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/EmptyLiteral:
  Enabled: false

Encoding:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false