amazonlinux_tag: 2018.03.0.20190826-with-sources
chef_client_version: 15.2.20
chefdk_version: 4.3.13
docker_repo: bonusbits
ec2_type: t3.micro
expose_port: 8081
internal_only: false
k8s_namespace: bonusbits
k8s_replica_count: 2
local_deploy: true
pod_port: 8081
project_name: bonusbits_base
