---
kind: Service
apiVersion: v1
metadata:
  annotations:
    author: Levon Becker
  labels:
    bonusbits.service: base
  name: base
  namespace: bonusbits
spec:
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  selector:
    bonusbits.app: base
  type: LoadBalancer
